ARG ALPINE_VERSION=3.20
FROM alpine:$ALPINE_VERSION
RUN echo "ยังไม่ประกาศซ้ำ ALPINE_VERSION=[$ALPINE_VERSION]"
ARG ALPINE_VERSION
RUN echo "ประกาศซ้ำแล้ว ALPINE_VERSION=[$ALPINE_VERSION]"
CMD ["sh","-c","cat /etc/alpine-release"]
