apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lab009
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: k8s-lab-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: lab009
spec:
  type: ClusterIP # เรียกได้จากเครือข่ายใน cluster
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: http
