apiVersion: v1
kind: Service
metadata:
  name: web-bad-range
  namespace: lab009
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: http
      nodePort: 3000 # ผิด: อยู่นอกช่วงที่อนุญาต
---
apiVersion: v1
kind: Service
metadata:
  name: web-duplicate
  namespace: lab009
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: http
      nodePort: 30080 # ผิด: ซ้ำกับ Service web
