apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: lab021
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # ขอพื้นที่โดยไม่ผูกชื่อ PV เอง
