apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lab016
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: k8s-lab-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DB_HOST
              value: db
            # ระบุเองเพื่อไม่ให้ชน Service env ชื่อ DB_PORT
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: skillspace
            - name: DB_USER
              value: opsuser
            # ดึงรหัสผ่านจาก Secret ไม่ฝังใน image
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
