services:
  traefik:
    image: traefik:v3.7.4
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --accesslog=true
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - labnet

  shop-ui:
    build: ../shop-ui
    labels:
      traefik.enable: "true"
      traefik.docker.network: labnet
      traefik.http.routers.shop.rule: PathPrefix(`/`)
      traefik.http.routers.shop.entrypoints: web
      traefik.http.routers.shop.priority: "1"
      traefik.http.routers.shop.service: shop-ui
      traefik.http.routers.shop-host.rule: Host(`app.lab`)
      traefik.http.routers.shop-host.entrypoints: web
      traefik.http.routers.shop-host.priority: "200"
      traefik.http.routers.shop-host.middlewares: host-marker@docker
      traefik.http.routers.shop-host.service: shop-ui
      traefik.http.services.shop-ui.loadbalancer.server.port: "8000"
      traefik.http.middlewares.host-marker.headers.customresponseheaders.X-Lab-Router: host-rule
    networks:
      - storefront

  users:
    image: traefik/whoami:v1.11
    labels:
      traefik.enable: "true"
      traefik.docker.network: labnet
      traefik.http.routers.users.rule: PathPrefix(`/api/users`)
      traefik.http.routers.users.entrypoints: web
      traefik.http.routers.users.priority: "100"
      traefik.http.routers.users.service: users
      traefik.http.services.users.loadbalancer.server.port: "80"
      traefik.http.middlewares.users-auth.basicauth.users: student:$$apr1$$7ARlTd5N$$jGMmet/ijVlVt2Z4XgHX90
      traefik.http.middlewares.users-rate.ratelimit.average: "2"
      traefik.http.middlewares.users-rate.ratelimit.period: 1s
      traefik.http.middlewares.users-rate.ratelimit.burst: "2"
    networks:
      - labnet

  orders:
    build: ../orders
    deploy:
      replicas: 3
    labels:
      traefik.enable: "true"
      traefik.docker.network: labnet
      traefik.http.routers.orders.rule: PathPrefix(`/api/orders`)
      traefik.http.routers.orders.entrypoints: web
      traefik.http.routers.orders.priority: "100"
      traefik.http.routers.orders.service: orders
      traefik.http.services.orders.loadbalancer.server.port: "8088"
    networks:
      - labnet

networks:
  labnet:
    name: labnet
  storefront:
    name: lab005-storefront
