apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lab008
spec:
  replicas: 2 # สองปลายทางเพื่อดูการกระจาย request
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: k8s-lab-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
