apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab008
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: k8s-lab-web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: API_BASE_URL
              value: "http://api:8000" # เรียกชื่อ Service แทน Pod IP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
