apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: lab013
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: k8s-lab-api:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DB_HOST
              value: db # เรียกฐานข้อมูลผ่านชื่อ Service
            - name: DB_PORT
              value: "5432" # กันชื่อ env อัตโนมัติของ Service มาทับค่า port
            - name: DB_NAME
              value: skillspace
            - name: DB_USER
              value: opsuser
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: lab013
spec:
  selector:
    app: api
  ports:
    - port: 8000
      targetPort: http
