apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: lab007
spec:
  selector:
    app: web # ส่ง request ไป Pod ของ web
  ports:
    - port: 3000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: lab007
spec:
  ingressClassName: nginx
  rules:
    - http: # ไม่กำหนด host เพื่อเปิดผ่าน localhost ได้
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
