server {
    listen 80;
    listen 8186;

    server_name netlab-web;
    root /usr/share/nginx/html;
    index index.html;

    add_header X-Lab-Service "netlab-web" always;

    location /healthz {
        add_header Content-Type text/plain;
        return 200 'ok';
    }
}
