services:
  traefik:
    image: traefik:v3.7.4
    command:
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --api.insecure=true
      - --entrypoints.web.address=:80
    ports:
      - "8000:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - labnet

  app:
    build: ./app
    labels:
      traefik.enable: "true"
      traefik.docker.network: "labnet"
      traefik.http.routers.lab2.rule: "PathPrefix(`/`)"
      traefik.http.routers.lab2.entrypoints: "web"
      traefik.http.routers.lab2.service: "lab2-app"
      traefik.http.routers.lab2-host.rule: "Host(`app.lab`)"
      traefik.http.routers.lab2-host.entrypoints: "web"
      traefik.http.routers.lab2-host.service: "lab2-app"
      traefik.http.services.lab2-app.loadbalancer.server.port: "8000"
      traefik.http.services.lab2-app.loadbalancer.healthcheck.path: "/health"
      traefik.http.services.lab2-app.loadbalancer.healthcheck.interval: "3s"
      traefik.http.services.lab2-app.loadbalancer.healthcheck.timeout: "1s"
    networks:
      - labnet

networks:
  labnet:
    name: labnet
