# LAB 6: Pod ลูกค้า (busybox) ยิง wget วนเข้า Service web
apiVersion: v1
kind: Pod
metadata:
  name: client
  namespace: broken-lab
  labels:
    role: client
spec:
  terminationGracePeriodSeconds: 1   # ลบแล้วหายเร็ว
  containers:
    - name: busybox
      image: busybox:1.36
      command: ["sleep", "infinity"]
      resources:
        requests: { cpu: 10m, memory: 16Mi }
        limits:   { cpu: 100m, memory: 32Mi }
