apiVersion: v1
kind: Pod
metadata:
  name: imagepull-web
  namespace: lab020
  labels:
    case: imagepull
spec:
  containers:
    - name: web
      image: k8s-lab-web:v1 # ใช้ tag ที่ build และ load แล้ว
      imagePullPolicy: IfNotPresent
