services:
  users:
    labels:
      traefik.http.routers.users.middlewares: ""
  orders:
    labels:
      traefik.http.routers.orders.middlewares: ""
  products:
    labels:
      traefik.http.routers.products.middlewares: ""
