# LAB 4: cache — ตู้เย็นของร้าน วางไว้บนเรือ lab-worker (ใช้ label มาตรฐาน kubernetes.io/hostname)
apiVersion: v1
kind: Pod
metadata:
  name: cache
  labels:
    lab: "03"
    app: cache                # web-near-cache จะ "ดึงดูด" Pod ที่มีป้ายนี้
spec:
  nodeSelector:
    kubernetes.io/hostname: lab-worker
  containers:
    - name: web
      image: nginx:1.27-alpine
