apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: lab011
spec:
  ingressClassName: nginx
  rules:
    - http: # ประตูเดียวเข้าสู่หน้าเว็บ
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
