pipeline {
    agent any

    environment {
        DOCKER_IMAGE    = 'tuchsanai/fastapi-webhook:latest' // Corrected the Docker image name
        REMOTE_HOST     = 'tuchsanai@34.124.197.62' // Username and remote IP should be updated with actual values
        SSH_CREDENTIALS = 'ssh_prod_instance' // SSH credentials should be replaced with your actual credentials
    }

    stages {

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {
                    sh 'echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USER --password-stdin'
                }
            }
        }

        stage('Run Docker on Remote Server') {
            steps {
                sshagent(['ssh_prod_instance']) {
                    // Corrected command to execute Docker run on the remote server
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker stop $(docker ps -a -q)'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker rm $(docker ps -a -q)'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker rmi $(docker images -q)'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker run -d --name fastapi-webhook -p 8085:80 $DOCKER_IMAGE'"
                    sh "ssh -o StrictHostKeyChecking=no $REMOTE_HOST 'docker ps -a'"
                 
                }
            }
        }
    }
}


