pipeline {
    agent any

    environment {
        DOCKER_IMAGE    = 'tuchsanai/fastapi-webhook:latestmage' // Replace with your Docker image
        REMOTE_HOST     = 'tuchsanai@34.124.197.62' // Replace username and remote_ip with actual values
        SSH_CREDENTIALS = 'ssh_prod_instance' // Replace with your SSH credentials
    }

    stages {

        stage('Login to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USER')]) {
                    sh 'echo $DOCKERHUB_PASSWORD | docker login --username $DOCKERHUB_USER --password-stdin'
                }
            }
        }

        stage('Run Docker on Remote Server') {
            steps {
                sshagent(['ssh_prod_instance']) {
                    // Replace your_docker_command with the actual Docker command you want to run on the remote server
                    sh 'ssh ${REMOTE_HOST}' 
                    sh 'docker stop $(docker ps -a -q)'  
                    sh  'docker rm $(docker ps -a -q)' 
                    sh  'docker rmi $(docker images -q)'
                    sh 'docker system prune -af'
                    sh 'docker pull ${DOCKER_IMAGE}'
                    sh 'docker run -d --name fastapi-webhook -p 8085:80 $DOCKER_IMAGE' 
                }
            }
        }
    }
}
