apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab010
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web # Service ใช้ label นี้หา Pod
    spec:
      containers:
        - name: web
          image: k8s-lab-web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: lab010
spec:
  selector:
    app: web
  ports:
    - port: 3000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: lab010
spec:
  ingressClassName: nginx
  rules:
    - http: # ไม่ใส่ host เพื่อเปิดผ่าน localhost ได้ตรง ๆ
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
