apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab010
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: k8s-lab-web:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom: # นำทุก key จาก ConfigMap เข้าเป็น environment variable
            - configMapRef:
                name: web-config
