# LAB 9: ใบเบิก 400Mi ในโซน quota-lab (ไม่ใส่ class → standard) — ดูว่างบพอไหม
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p400
  namespace: quota-lab
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 400Mi
