apiVersion: v1
kind: Pod
metadata:
  name: crashloop-web
  namespace: lab020
  labels:
    case: crashloop
spec:
  containers:
    - name: web
      image: k8s-lab-web:v1
      imagePullPolicy: IfNotPresent
      command: ["node", "missing.js"] # จงใจสั่งไฟล์ที่ไม่มี
