import { headers } from "next/headers";
import { apiGet, type Sales } from "../lib/api";
import { MENU_META } from "../ui";

export const dynamic="force-dynamic";
export default async function Dashboard(){const incoming=await headers();const auth=incoming.get("authorization")??undefined;const report=await apiGet<Sales>("/api/report/sales",auth);const max=Math.max(...report.items.map(x=>x.cups),1);return <>
  <section className="mb-7 overflow-hidden rounded-[2rem] bg-gradient-to-br from-coffee-950 to-coffee-700 px-8 py-8 text-white shadow-xl"><p className="text-xs font-bold tracking-[.22em] text-caramel-400">OWNER INSIGHT · TREND LEVEL</p><h1 className="mt-1 text-4xl font-black">ภาพรวมร้านวันนี้</h1><p className="mt-2 max-w-2xl text-cream-200">ตัวเลขจากเหตุการณ์ ORDER_PLACED สำหรับมองแนวโน้มวัตถุดิบ ไม่ใช่ยอดปิดบัญชี</p></section>
  <section className="mb-6 grid gap-4 sm:grid-cols-3"><div className="rounded-[1.5rem] border border-coffee-900/10 bg-white p-6 shadow-lg shadow-coffee-900/5"><p className="text-sm font-bold text-coffee-700">แก้วที่สั่งทั้งหมด</p><b className="mt-2 block text-5xl font-black">{report.totals.cups}</b><span className="text-xs text-caramel-500">TOTAL CUPS</span></div><div className="rounded-[1.5rem] bg-caramel-500 p-6 text-white shadow-lg shadow-caramel-500/20"><p className="text-sm font-bold text-orange-100">ยอดสะสมโดยประมาณ</p><b className="mt-2 block text-5xl font-black">฿{report.totals.revenue.toFixed(2)}</b><span className="text-xs text-orange-100">TREND REVENUE</span></div><div className="rounded-[1.5rem] border border-coffee-900/10 bg-white p-6 shadow-lg shadow-coffee-900/5"><p className="text-sm font-bold text-coffee-700">เมนูในระบบ</p><b className="mt-2 block text-5xl font-black">{report.items.length}</b><span className="text-xs text-emerald-700">ครบทุกเมนู</span></div></section>
  <section className="rounded-[1.7rem] border border-coffee-900/10 bg-white p-6 shadow-lg shadow-coffee-900/5"><div className="mb-6"><p className="text-xs font-bold tracking-[.2em] text-caramel-500">MENU PERFORMANCE</p><h2 className="text-2xl font-black">ยอดแก้วแยกตามเมนู</h2></div><div className="space-y-5">{report.items.map(item=><div key={item.menu_code} className="grid items-center gap-3 sm:grid-cols-[12rem_1fr_8rem]"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-cream-100 text-xl">{MENU_META[item.menu_code]?.emoji}</span><div><b className="block">{item.name_th}</b><small className="text-coffee-700">฿{item.revenue.toFixed(2)}</small></div></div><div className="h-3 overflow-hidden rounded-full bg-cream-200"><div className="h-full rounded-full bg-gradient-to-r from-caramel-400 to-caramel-500" style={{width:`${Math.max(item.cups/max*100,item.cups?5:0)}%`}}/></div><div className="text-right"><b className="text-2xl tabular-nums">{item.cups}</b><span className="ml-1 text-xs text-coffee-700">แก้ว</span></div></div>)}</div></section>
  </>}
