apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
    version: v2 # label บอกเวอร์ชันให้ค้นหาได้ภายหลัง
spec:
  containers:
    - name: web
      image: k8s-lab-web:v2 # เปลี่ยน desired state จาก v1 เป็น v2
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 3000
