# LAB 2: HPA แบบ YAML (เท่ากับ kubectl autoscale deployment php-apache --cpu=50% --min=1 --max=6)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-apache
  namespace: hpa-demo
spec:
  scaleTargetRef:              # ใครคือเป้าหมาย (ต้องมี subresource /scale: Deployment, StatefulSet, ReplicaSet)
    apiVersion: apps/v1
    kind: Deployment
    name: php-apache
  minReplicas: 1
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization    # % ของ requests.cpu (100m) → 50% = เฉลี่ย 50m ต่อ Pod
          averageUtilization: 50
