# LAB 4: สองโซนของสองทีม
apiVersion: v1
kind: Namespace                  # ไฟล์เดียวสร้าง 2 โซน (คั่นด้วย ---)
metadata:
  name: team-a                   # โซนของทีม a
  labels:
    team: a                      # label ที่เราตั้งเอง
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-b                   # โซนของทีม b
  labels:
    team: b                      # label ที่เราตั้งเอง
