http:
  routers:
    canary-router:
      entryPoints:
        - web
      rule: PathPrefix(`/canary`)
      service: canary

    mirror-router:
      entryPoints:
        - web
      rule: PathPrefix(`/mirror`)
      service: mirrored

    host-exercise-router:
      entryPoints:
        - web
      rule: Host(`app.lab`)
      service: canary
      priority: 1

  services:
    canary:
      weighted:
        services:
          - name: v1@docker
            weight: 9
          - name: v2@docker
            weight: 1

    mirrored:
      mirroring:
        service: v1@docker
        mirrors:
          - name: v2@docker
            percent: 100
